cj_rotationTable = {
[12] = "CJFrostDKRot",
[21] = "CJBalanceDruidRot",
[22] = "CJFeralDruidRot",
[41] = "CJArcMageRot",
[42] = "CJFireMageRot",
[52] = "CJProtPallyRot",
[53] = "CJRetPallyRot",
[81] = "CJEleShamRot",
[82] = "CJEnhShamRot"
};

cj_interruptBlacklist = {
	["High Priestess Kilnara"] = {[1] = "Shadow Bolt"},
	["Venomancer Mauri"] = {[1] = "Poison Bolt"},
	["Hex Lord Malacrass"] = {[1] = "Chain Lightning",[2] = "Mind Blast"},
	["Maloriak"] = {[1] = "Release Aberrations"},
	["Naz'jar Spiritmender"] = {[1] = "Wrath"},
	["Stonecore Rift Conjurer"] = {[1] = "Shadow Bolt"},
	["Temple Adept"] = {[1] = "Holy Smite"},
	["Stonecore Earthshaper"] = {[1] = "Lava Burst",[2] = "Ground Shock"}
};

cj_bosslist = {
	[1] = "Admiral Ripsnarl",
	[2] = "Altairus",
	[3] = "Ammunae",
	[4] = "Anraphet",
	[5] = "Argaloth",
	[6] = "Asaad",
	[7] = "Ascendant Lord Obsidius",
	[8] = "Augh",
	[9] = "Beauty",
	[10] = "Chimaeron",
	[11] = "Commander Ulthok",
	[12] = "Corborus",
	[13] = "Corla, Herald of Twilight",
	[14] = "Drahga Shadowburner",
	[15] = "Earthrager Ptah",
	[16] = "Elementium Monstrosity",
	[17] = "Erudax",
	[18] = "Erunak Stonespeaker",
	[19] = "Foe Reaper 5000",
	[20] = "Forgemaster Throngus",
	[21] = "General Husam",
	[22] = "General Umbriss",
	[23] = "Glubtok",
	[24] = "Grand Vizier Ertan",
	[25] = "Halfus Wyrmbreaker",
	[25] = "Helix Gearbreaker",
	[26] = "High Priestess Azil",
	[28] = "High Prophet Barim",
	[29] = "Isiset",
	[30] = "Karsh Steelbender",
	[31] = "Lady Naz'jar",
	[32] = "Lockmaw",
	[33] = "Mindbender Ghur'sha",
	[34] = "Nefarian",
	[35] = "Ozruk",
	[36] = "Ozumat",
	[37] = "Rajh",
	[38] = "Rom'ogg Bonecrusher",
	[39] = "Setesh",
	[40] = "Siamat",
	[41] = "Slabhide",
	[42] = "Temple Guardian Anhuur",
	[43] = "Valiona",
	[44] = "Vanessa VanCleef",
	[45] = "Arcanotron",
	[46] = "Arion",
	[58] = "Atramedes",
	[49] = "Cho'gall",
	[50] = "Electron",
	[51] = "Magmatron",
	[52] = "Toxitron",
	[54] = "Feludius",
	[55] = "Ignacious",
	[56] = "Magmaw",
	[57] = "Maloriak",
	[58] = "Nezir",
	[59] = "Rohash",
	[60] = "Sinestra",
	[61] = "Terrastra",
	[62] = "Anshal",
	[63] = "Al'Akir",
	[64] = "Akil'zon",
	[65] = "Nalorakk",
	[66] = "Jan'alai",
	[67] = "Halazzi",
	[68] = "Hex Lord Malacrass",
	[69] = "Daakara",
	[70] = "High Priest Venoxis",
	[71] = "Bloodlord Mandokir",
	[72] = "Hazza'rah",
	[73] = "Renataki",
	[74] = "Wushoolay",
	[75] = "Gri'lek",
	[76] = "High Priestess Kilnara",
	[77] = "Zan'zil",
	[78] = "Jin'do the Godbreaker"
};